"""Operation service — Execution Planner (Sprint 6A).

Reviews, configures, and approves execution plan generated by Requirement layer.
Never creates execution plans or calculates estimates.
"""

from typing import Any, Callable, Dict, List, Optional
from dav_platform.core.contracts import ExecutionStep, OperationContext

PIPELINE_STAGES_DEMO = [
    {"id": "load", "label": "Load", "icon": "upload_file", "purpose": "Load canonical dataset from mapped source", "duration": "~30 sec", "dependencies": "Project, Connection, Detection, Mapping"},
    {"id": "aggregate", "label": "Aggregate", "icon": "functions", "purpose": "Aggregate data by selected dimensions", "duration": "~1 min", "dependencies": "Load complete"},
    {"id": "calculate", "label": "Calculate", "icon": "calculate", "purpose": "Calculate derived metrics and KPIs", "duration": "~1 min", "dependencies": "Aggregate complete"},
    {"id": "validate", "label": "Validate", "icon": "verified", "purpose": "Validate results against business rules", "duration": "~1 min", "dependencies": "Calculate complete"},
    {"id": "reports", "label": "Generate Reports", "icon": "assessment", "purpose": "Generate Excel, CSV, and summary reports", "duration": "~30 sec", "dependencies": "Validate complete"},
    {"id": "export", "label": "Export", "icon": "download", "purpose": "Export all outputs to configured destinations", "duration": "~30 sec", "dependencies": "Reports complete"},
]

DEFAULT_CONFIG = {
    "streaming": True,
    "chunk_size": 10000,
    "parallel_workers": 2,
    "output_location": "./output",
    "dry_run": False,
}

RESOURCE_ESTIMATES_BASE = {
    "runtime": "3-5 min",
    "memory": "256 MB",
    "peak_memory": "512 MB",
    "cpu": "2 cores",
    "streaming": True,
    "rows": "1,250",
    "output_size": "~5 MB",
}

READINESS_ITEMS = [
    {"id": "project_ready", "label": "Project Ready"},
    {"id": "connection_ready", "label": "Connection Ready"},
    {"id": "detection_complete", "label": "Detection Complete"},
    {"id": "mapping_complete", "label": "Mapping Complete"},
    {"id": "preview_approved", "label": "Preview Approved"},
    {"id": "analysis_planned", "label": "Analysis Planned"},
    {"id": "ready_to_execute", "label": "Ready to Execute"},
]


class OperationService:
    """Manages Execution Planner state.

    Consumes OperationContext from Requirement layer.
    Never creates execution plans or calculates estimates.
    """

    def __init__(self, req_svc=None):
        self._req = req_svc
        self._config: Dict[str, Any] = dict(DEFAULT_CONFIG)
        self._approved: bool = False
        self._on_change: Optional[Callable] = None

    # ── Pipeline ─────────────────────────────────────────────

    @property
    def pipeline_stages(self) -> List[Dict[str, Any]]:
        return list(PIPELINE_STAGES_DEMO)

    # ── Backend OperationContext ─────────────────────────────

    @property
    def operation_context(self) -> Optional[OperationContext]:
        if self._req and hasattr(self._req, "get_operation_context"):
            try:
                return self._req.get_operation_context()
            except Exception:
                return None
        return None

    # ── Execution Steps (from Requirement) ───────────────────

    @property
    def execution_steps(self) -> List[ExecutionStep]:
        ctx = self.operation_context
        if ctx and ctx.execution_plan:
            return list(ctx.execution_plan)
        if self._req and hasattr(self._req, 'execution_plan'):
            return self._req.execution_plan
        return []

    @property
    def execution_summary(self) -> Dict[str, Any]:
        steps = self.execution_steps
        return {
            "total_steps": len(steps),
            "required_steps": sum(1 for s in steps if s.required),
            "layers": list(dict.fromkeys(s.layer for s in steps)),
            "mode": self._get_execution_mode(),
        }

    def _get_execution_mode(self) -> str:
        if self._req and hasattr(self._req, 'selected_goal'):
            g = self._req.selected_goal
            if g:
                return g["mode"].value.replace("_", " ").title()
        return "Aggregate Only"

    # ── Configuration ────────────────────────────────────────

    @property
    def config(self) -> Dict[str, Any]:
        return dict(self._config)

    def update_config(self, **kwargs) -> None:
        self._config.update(kwargs)
        self._notify()

    def set_config(self, key: str, value: Any) -> None:
        self._config[key] = value
        self._notify()

    def reset_config(self) -> None:
        self._config = dict(DEFAULT_CONFIG)
        self._notify()

    # ── Resource Estimates ───────────────────────────────────

    @property
    def resource_estimates(self) -> Dict[str, Any]:
        estimates = dict(RESOURCE_ESTIMATES_BASE)
        if self._config.get("streaming"):
            estimates["memory"] = "128 MB"
            estimates["peak_memory"] = "256 MB"
        if self._config.get("dry_run"):
            estimates["runtime"] = "< 30 sec"
        return estimates

    # ── Expected Outputs (from Requirement) ──────────────────

    @property
    def expected_outputs(self) -> List[str]:
        if self._req and hasattr(self._req, 'expected_outputs'):
            return self._req.expected_outputs
        return ["Execution Summary", "Processed Dataset (CSV)"]

    # ── Readiness ────────────────────────────────────────────

    @property
    def readiness_items(self) -> List[Dict[str, Any]]:
        items = []
        for item in READINESS_ITEMS:
            items.append({
                "id": item["id"],
                "label": item["label"],
                "status": self._get_readiness_status(item["id"]),
            })
        return items

    def _get_readiness_status(self, item_id: str) -> bool:
        if item_id == "project_ready":
            return True
        elif item_id == "connection_ready":
            return True
        elif item_id == "detection_complete":
            return True
        elif item_id == "mapping_complete":
            return True
        elif item_id == "preview_approved":
            return True
        elif item_id == "analysis_planned":
            if self._req is not None:
                return getattr(self._req, 'is_confirmed', False)
            return True  # standalone: assume ready
        elif item_id == "ready_to_execute":
            return all(
                self._get_readiness_status(i["id"])
                for i in READINESS_ITEMS
                if i["id"] != "ready_to_execute"
            )
        return False

    @property
    def overall_readiness(self) -> str:
        all_ready = all(i["status"] for i in self.readiness_items)
        return "Ready to Execute" if all_ready else "Review Required"

    # ── Approval ─────────────────────────────────────────────

    @property
    def is_approved(self) -> bool:
        return self._approved

    @property
    def can_approve(self) -> bool:
        return self.overall_readiness == "Ready to Execute"

    def approve(self) -> None:
        if self.can_approve:
            self._approved = True
            self._notify()

    def reject(self) -> None:
        self._approved = False
        self._notify()

    # ── Events ──────────────────────────────────────────────

    def on_change(self, callback: Callable) -> None:
        self._on_change = callback

    def _notify(self) -> None:
        if self._on_change:
            self._on_change()
